<a href="https://colab.research.google.com/github/luizfsjunior/data-science/blob/main/pr%C3%A9_processamento_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1. Faça a leitura do arquivo "Churn_Modelling_2.csv" disponível na pasta "Churn" no repositório GitHub da disciplina e armazene numa variável como um dataframe:

In [1]:
!git clone "https://github.com/malegopc/DSBD"

Cloning into 'DSBD'...
remote: Enumerating objects: 507, done.
remote: Counting objects: 100% (50/50), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 507 (delta 19), reused 0 (delta 0), pack-reused 457
Receiving objects: 100% (507/507), 9.15 MiB | 19.37 MiB/s, done.
Resolving deltas: 100% (227/227), done.


In [2]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.model_selection import train_test_split

In [117]:
churn = pd.read_csv('DSBD/Datasets/Churn/Churn_Modelling_2.csv', na_values=['?'])
if churn.isnull().values.any()== True:
  print("Há dados vazios")
else:
  print("Não há dados vazios")
churn


Há dados vazios


RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00            1.0          1             1.0   
1          1   83807.86            1.0          0             1.0   
2          8  159660.80            3.0          1             0.0   
3          1       0.00            2.0          0             0.0   
4          2  125510.82            1.0          1             1.0   
...      ...        ...            ...        ...             ...   
9995       5       0.00            2.0          1             0.0   
9996      10   57369.61            1.0          1             1.0   
9997       7       0.00            1.0          0             1.0   
9998       3   75075.31            2.0          1             0.0   
9999       4  130142.79            1.0          1             0.0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

##2. Elimine instâncias (linhas) com dados ausentes para a variável "IsActiveMember":

In [118]:
# Mostra o número de dados non-null (não ausentes) e o tipo de cada atributo
print('Informações sobre os dados:\n')
churn.info()
# Soma o número de dados null (ausentes)
print('\n\nSoma de dados null (vazios):\n')
churn.isnull().sum()

Informações sobre os dados:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    9990 non-null   float64
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   9986 non-null   float64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(4), int64(7), object(3)
memory usage: 1.1+ MB


Soma de dados null (vazios):



RowNumber           0
CustomerId          0
Surname             0
CreditScore         0
Geography           0
Gender              0
Age                 0
Tenure              0
Balance             0
NumOfProducts      10
HasCrCard           0
IsActiveMember     14
EstimatedSalary     0
Exited              0
dtype: int64

In [119]:
churn = churn.dropna(inplace = False, subset = ['IsActiveMember'])


##3. Faça a imputação dos dados ausentes para a variável "NumOfProducts" utilizando a média da variável:

In [120]:
churn2 = churn.copy()
imputer = SimpleImputer(missing_values = np.nan, strategy ='mean')
churn2[['NumOfProducts']] = imputer.fit_transform(churn2[['NumOfProducts']].values)


print('\n\nSoma de dados null (vazios):\n')
churn2.isnull().sum()



Soma de dados null (vazios):



RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

##4. Crie uma variável (array) X que contenha os valores apenas dos atributos/colunas de "CreditScore" a "EstimatedSalary" utilizando a função "iloc" do Pandas. Em outras palavras, crie uma variável X que receba o dataframe inteiro exceto as 3 primeiras colunas e a última. Observe que as 3 primeiras colunas "RowNumber", "CustomerId" e "Surname" não são importantes e devem ser descartadas. E a última coluna ("Exited") será a variável destino ("target" ou saída) que será criada no próximo passo:

In [121]:
x = churn2.iloc[:, 3:13].values
print(x)

[[619 'France' 'Female' ... 1 1.0 101348.88]
 [608 'Spain' 'Female' ... 0 1.0 112542.58]
 [502 'France' 'Female' ... 1 0.0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1.0 42085.58]
 [772 'Germany' 'Male' ... 1 0.0 92888.52]
 [792 'France' 'Female' ... 1 0.0 38190.78]]


##5. Crie uma variável (array) y que contenha apenas a última coluna  ("Exited"). Esta é a variável destino ("target" ou saída):

In [122]:
y = churn2['Exited']

##6. Codifique a coluna/variável categórica "Geography" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

##7. Codifique a coluna/variável categórica "Gender" como numérica utilizando a classe LabelEncoder da biblioteca scikit-learn;

##8. Após executar o passo 6, transforme os dados da variável "Geography" para a forma binária utilizando a classe OneHotEncoder da biblioteca scikit-learn eliminando redundância, ou seja, aplicando a codificação de variáveis dummy. Observe que há apenas 3 países (categorias) diferentes. Atenção: esse talvez seja o passo mais difícil da tarefa. Você deve transformar o resultado da variável/coluna "Geography" obtido no passo 4 para o formato binário (one-hot) de modo que fique representado por apenas duas colunas (de 0s e 1s). Além disso, essas duas novas colunas devem permanecer na mesma variável X. Dica: verifique a utilização da função make_column_transformer da biblioteca scikit-learn:


In [123]:
enc_geo = OneHotEncoder(drop = 'first', sparse = False)
enc_gen = OneHotEncoder(sparse = False)
ct = make_column_transformer(
      (enc_geo,[1]), (enc_gen,[2]), remainder = 'passthrough')
x = ct.fit_transform(x)
print(x)

[[0.0 0.0 1.0 ... 1 1.0 101348.88]
 [0.0 1.0 1.0 ... 0 1.0 112542.58]
 [0.0 0.0 1.0 ... 1 0.0 113931.57]
 ...
 [0.0 0.0 1.0 ... 0 1.0 42085.58]
 [1.0 0.0 0.0 ... 1 0.0 92888.52]
 [0.0 0.0 1.0 ... 1 0.0 38190.78]]


##9. Divida as variáveis X e y em dados de treino e de teste utilizando o método "train_test_split", gerando as variáveis X_train, X_test, y_train e y_test. Você define a proporção de dados de treino e de teste:

In [129]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.20,random_state=42)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((7988, 12), (1998, 12), (7988,), (1998,))

##10. Faça a padronização (escalonamento) dos dados das variáveis X_train e X_test utilizando a classe StandardScaler do scikit-learn:

In [130]:
sc = StandardScaler()
x_train= sc.fit_transform(x_train)
x_test = sc.transform(x_test)

[[-0.57831397 -0.57368819 -0.90852151 ... -1.55689361 -1.03335518
   1.17467225]
 [-0.57831397  1.74310718  1.1006894  ...  0.64230465 -1.03335518
  -1.4473007 ]
 [-0.57831397 -0.57368819  1.1006894  ... -1.55689361  0.96772147
  -0.43412315]
 ...
 [-0.57831397 -0.57368819  1.1006894  ...  0.64230465 -1.03335518
   1.56483088]
 [-0.57831397 -0.57368819  1.1006894  ...  0.64230465  0.96772147
  -1.26073874]
 [-0.57831397 -0.57368819 -0.90852151 ...  0.64230465  0.96772147
   1.56707508]]
